/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Booking {
  'id' : bigint,
  'ref' : BookingRef,
  'merchantName' : string,
  'duration' : DurationPackage,
  'paymentMethod' : PaymentMethod,
  'rentalPrice' : bigint,
  'createdAt' : Timestamp,
  'deposit' : bigint,
  'nationalId' : string,
  'bookingDate' : string,
  'storeType' : StoreType,
  'totalPrice' : bigint,
}
export type BookingRef = string;
export interface BookingRequest {
  'merchantName' : string,
  'duration' : DurationPackage,
  'paymentMethod' : PaymentMethod,
  'nationalId' : string,
  'bookingDate' : string,
  'storeType' : StoreType,
}
export type DurationPackage = { 'fourHours' : null } |
  { 'oneHour' : null } |
  { 'twoHours' : null } |
  { 'fullDay' : null } |
  { 'threeHours' : null } |
  { 'weekly' : null };
export type PaymentMethod = { 'cash' : null } |
  { 'electronic' : null };
export type StoreType = { 'large' : null } |
  { 'small' : null };
export type Timestamp = bigint;
export interface _SERVICE {
  'getAllBookings' : ActorMethod<[], Array<Booking>>,
  'getBooking' : ActorMethod<[BookingRef], [] | [Booking]>,
  'getBookingCount' : ActorMethod<[], bigint>,
  'getBookingsByDate' : ActorMethod<[string], Array<Booking>>,
  'submitBooking' : ActorMethod<[BookingRequest], BookingRef>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];