/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BookingRef = IDL.Text;
export const DurationPackage = IDL.Variant({
  'fourHours' : IDL.Null,
  'oneHour' : IDL.Null,
  'twoHours' : IDL.Null,
  'fullDay' : IDL.Null,
  'threeHours' : IDL.Null,
  'weekly' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({
  'cash' : IDL.Null,
  'electronic' : IDL.Null,
});
export const Timestamp = IDL.Int;
export const StoreType = IDL.Variant({
  'large' : IDL.Null,
  'small' : IDL.Null,
});
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'ref' : BookingRef,
  'merchantName' : IDL.Text,
  'duration' : DurationPackage,
  'paymentMethod' : PaymentMethod,
  'rentalPrice' : IDL.Nat,
  'createdAt' : Timestamp,
  'deposit' : IDL.Nat,
  'nationalId' : IDL.Text,
  'bookingDate' : IDL.Text,
  'storeType' : StoreType,
  'totalPrice' : IDL.Nat,
});
export const BookingRequest = IDL.Record({
  'merchantName' : IDL.Text,
  'duration' : DurationPackage,
  'paymentMethod' : PaymentMethod,
  'nationalId' : IDL.Text,
  'bookingDate' : IDL.Text,
  'storeType' : StoreType,
});

export const idlService = IDL.Service({
  'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
  'getBooking' : IDL.Func([BookingRef], [IDL.Opt(Booking)], ['query']),
  'getBookingCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getBookingsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
  'submitBooking' : IDL.Func([BookingRequest], [BookingRef], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BookingRef = IDL.Text;
  const DurationPackage = IDL.Variant({
    'fourHours' : IDL.Null,
    'oneHour' : IDL.Null,
    'twoHours' : IDL.Null,
    'fullDay' : IDL.Null,
    'threeHours' : IDL.Null,
    'weekly' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({
    'cash' : IDL.Null,
    'electronic' : IDL.Null,
  });
  const Timestamp = IDL.Int;
  const StoreType = IDL.Variant({ 'large' : IDL.Null, 'small' : IDL.Null });
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'ref' : BookingRef,
    'merchantName' : IDL.Text,
    'duration' : DurationPackage,
    'paymentMethod' : PaymentMethod,
    'rentalPrice' : IDL.Nat,
    'createdAt' : Timestamp,
    'deposit' : IDL.Nat,
    'nationalId' : IDL.Text,
    'bookingDate' : IDL.Text,
    'storeType' : StoreType,
    'totalPrice' : IDL.Nat,
  });
  const BookingRequest = IDL.Record({
    'merchantName' : IDL.Text,
    'duration' : DurationPackage,
    'paymentMethod' : PaymentMethod,
    'nationalId' : IDL.Text,
    'bookingDate' : IDL.Text,
    'storeType' : StoreType,
  });
  
  return IDL.Service({
    'getAllBookings' : IDL.Func([], [IDL.Vec(Booking)], []),
    'getBooking' : IDL.Func([BookingRef], [IDL.Opt(Booking)], ['query']),
    'getBookingCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getBookingsByDate' : IDL.Func([IDL.Text], [IDL.Vec(Booking)], ['query']),
    'submitBooking' : IDL.Func([BookingRequest], [BookingRef], []),
  });
};

export const init = ({ IDL }) => { return []; };