/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Timestamp = bigint;
export interface BookingRequest {
    merchantName: string;
    duration: DurationPackage;
    paymentMethod: PaymentMethod;
    nationalId: string;
    bookingDate: string;
    storeType: StoreType;
}
export type BookingRef = string;
export interface Booking {
    id: bigint;
    ref: BookingRef;
    merchantName: string;
    duration: DurationPackage;
    paymentMethod: PaymentMethod;
    rentalPrice: bigint;
    createdAt: Timestamp;
    deposit: bigint;
    nationalId: string;
    bookingDate: string;
    storeType: StoreType;
    totalPrice: bigint;
}
export enum DurationPackage {
    fourHours = "fourHours",
    oneHour = "oneHour",
    twoHours = "twoHours",
    fullDay = "fullDay",
    threeHours = "threeHours",
    weekly = "weekly"
}
export enum PaymentMethod {
    cash = "cash",
    electronic = "electronic"
}
export enum StoreType {
    large = "large",
    small = "small"
}
export interface backendInterface {
    getAllBookings(): Promise<Array<Booking>>;
    getBooking(ref: BookingRef): Promise<Booking | null>;
    getBookingCount(): Promise<bigint>;
    getBookingsByDate(date: string): Promise<Array<Booking>>;
    submitBooking(req: BookingRequest): Promise<BookingRef>;
}
import type { Booking as _Booking, BookingRef as _BookingRef, BookingRequest as _BookingRequest, DurationPackage as _DurationPackage, PaymentMethod as _PaymentMethod, StoreType as _StoreType, Timestamp as _Timestamp } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async getAllBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllBookings();
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllBookings();
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBooking(arg0: BookingRef): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBooking(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBooking(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingCount(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingCount();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingCount();
            return result;
        }
    }
    async getBookingsByDate(arg0: string): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingsByDate(arg0);
                return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingsByDate(arg0);
            return from_candid_vec_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitBooking(arg0: BookingRequest): Promise<BookingRef> {
        if (this.processError) {
            try {
                const result = await this.actor.submitBooking(to_candid_BookingRequest_n11(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitBooking(to_candid_BookingRequest_n11(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
function from_candid_Booking_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_DurationPackage_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DurationPackage): DurationPackage {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n7(_uploadFile, _downloadFile, value);
}
function from_candid_StoreType_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoreType): StoreType {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    ref: _BookingRef;
    merchantName: string;
    duration: _DurationPackage;
    paymentMethod: _PaymentMethod;
    rentalPrice: bigint;
    createdAt: _Timestamp;
    deposit: bigint;
    nationalId: string;
    bookingDate: string;
    storeType: _StoreType;
    totalPrice: bigint;
}): {
    id: bigint;
    ref: BookingRef;
    merchantName: string;
    duration: DurationPackage;
    paymentMethod: PaymentMethod;
    rentalPrice: bigint;
    createdAt: Timestamp;
    deposit: bigint;
    nationalId: string;
    bookingDate: string;
    storeType: StoreType;
    totalPrice: bigint;
} {
    return {
        id: value.id,
        ref: value.ref,
        merchantName: value.merchantName,
        duration: from_candid_DurationPackage_n4(_uploadFile, _downloadFile, value.duration),
        paymentMethod: from_candid_PaymentMethod_n6(_uploadFile, _downloadFile, value.paymentMethod),
        rentalPrice: value.rentalPrice,
        createdAt: value.createdAt,
        deposit: value.deposit,
        nationalId: value.nationalId,
        bookingDate: value.bookingDate,
        storeType: from_candid_StoreType_n8(_uploadFile, _downloadFile, value.storeType),
        totalPrice: value.totalPrice
    };
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    fourHours: null;
} | {
    oneHour: null;
} | {
    twoHours: null;
} | {
    fullDay: null;
} | {
    threeHours: null;
} | {
    weekly: null;
}): DurationPackage {
    return "fourHours" in value ? DurationPackage.fourHours : "oneHour" in value ? DurationPackage.oneHour : "twoHours" in value ? DurationPackage.twoHours : "fullDay" in value ? DurationPackage.fullDay : "threeHours" in value ? DurationPackage.threeHours : "weekly" in value ? DurationPackage.weekly : value;
}
function from_candid_variant_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cash: null;
} | {
    electronic: null;
}): PaymentMethod {
    return "cash" in value ? PaymentMethod.cash : "electronic" in value ? PaymentMethod.electronic : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    large: null;
} | {
    small: null;
}): StoreType {
    return "large" in value ? StoreType.large : "small" in value ? StoreType.small : value;
}
function from_candid_vec_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n2(_uploadFile, _downloadFile, x));
}
function to_candid_BookingRequest_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BookingRequest): _BookingRequest {
    return to_candid_record_n12(_uploadFile, _downloadFile, value);
}
function to_candid_DurationPackage_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DurationPackage): _DurationPackage {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function to_candid_StoreType_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoreType): _StoreType {
    return to_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function to_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    merchantName: string;
    duration: DurationPackage;
    paymentMethod: PaymentMethod;
    nationalId: string;
    bookingDate: string;
    storeType: StoreType;
}): {
    merchantName: string;
    duration: _DurationPackage;
    paymentMethod: _PaymentMethod;
    nationalId: string;
    bookingDate: string;
    storeType: _StoreType;
} {
    return {
        merchantName: value.merchantName,
        duration: to_candid_DurationPackage_n13(_uploadFile, _downloadFile, value.duration),
        paymentMethod: to_candid_PaymentMethod_n15(_uploadFile, _downloadFile, value.paymentMethod),
        nationalId: value.nationalId,
        bookingDate: value.bookingDate,
        storeType: to_candid_StoreType_n17(_uploadFile, _downloadFile, value.storeType)
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DurationPackage): {
    fourHours: null;
} | {
    oneHour: null;
} | {
    twoHours: null;
} | {
    fullDay: null;
} | {
    threeHours: null;
} | {
    weekly: null;
} {
    return value == DurationPackage.fourHours ? {
        fourHours: null
    } : value == DurationPackage.oneHour ? {
        oneHour: null
    } : value == DurationPackage.twoHours ? {
        twoHours: null
    } : value == DurationPackage.fullDay ? {
        fullDay: null
    } : value == DurationPackage.threeHours ? {
        threeHours: null
    } : value == DurationPackage.weekly ? {
        weekly: null
    } : value;
}
function to_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    cash: null;
} | {
    electronic: null;
} {
    return value == PaymentMethod.cash ? {
        cash: null
    } : value == PaymentMethod.electronic ? {
        electronic: null
    } : value;
}
function to_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoreType): {
    large: null;
} | {
    small: null;
} {
    return value == StoreType.large ? {
        large: null
    } : value == StoreType.small ? {
        small: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
